# Generated by Django 3.2 on 2021-05-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_path',
        ),
    ]
