# Generated by Django 3.2 on 2021-05-17 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import folder.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['created'], 'verbose_name_plural': 'Files'},
        ),
        migrations.RemoveField(
            model_name='file',
            name='author',
        ),
        migrations.RemoveField(
            model_name='file',
            name='fileData',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default='media/test.txt', upload_to=folder.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='file',
            name='file_path',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(default='None', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
