# Generated by Django 3.2 on 2021-05-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_remove_file_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_content',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_name',
            new_name='title',
        ),
    ]
