# Generated by Django 3.2 on 2021-05-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_auto_20210518_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='f_tag',
            field=models.CharField(default='None', max_length=200, verbose_name='남녀명수'),
        ),
    ]
