# Generated by Django 3.2 on 2021-05-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_auto_20210510_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.ImageField(default='media/logo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
