# Generated by Django 3.2 on 2021-05-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0003_alter_post_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='loc',
            field=models.CharField(default='.', max_length=200),
        ),
    ]
