# Generated by Django 3.2 on 2021-05-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0003_auto_20210514_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_path',
            field=models.CharField(default='.', max_length=200),
        ),
    ]
