# Generated by Django 3.2 on 2021-05-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0003_auto_20210511_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['created'], 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(default='media/logo.png', upload_to='timeline_file/%Y/%m/%d'),
        ),
    ]
