# Generated by Django 3.2 on 2021-05-14 14:47

from django.db import migrations, models
import folder.models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0004_file_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default='media/test.txt', upload_to=folder.models.get_upload_path),
        ),
    ]
