# Generated by Django 3.2 on 2021-05-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0004_auto_20210511_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default='media/test.txt', upload_to='timeline_file/%Y/%m/%d'),
        ),
    ]
