# Generated by Django 3.2 on 2021-05-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0004_alter_post_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_type',
            field=models.CharField(default='None', max_length=20, verbose_name='파일 타입'),
        ),
    ]
