# Generated by Django 3.2 on 2021-05-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0005_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='image',
        ),
    ]
