# Generated by Django 3.2 on 2021-05-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0007_alter_post_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_type',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
    ]
