# Generated by Django 3.2 on 2021-05-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0008_alter_post_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='f_tag',
            field=models.CharField(default='None', max_length=200, verbose_name='남녀명수'),
        ),
    ]
