# Generated by Django 3.2 on 2021-05-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0010_auto_20210531_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='f_size',
            field=models.IntegerField(default=0, verbose_name='파일용량'),
        ),
    ]
