# Generated by Django 3.2 on 2021-05-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0011_post_f_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
        migrations.AddField(
            model_name='file',
            name='loc',
            field=models.CharField(default='.', max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=30, upload_to=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
    ]
