# Generated by Django 3.2 on 2021-05-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0012_auto_20210531_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='f_tag',
            field=models.TextField(default='None', max_length=200, verbose_name='남녀명수'),
        ),
    ]
