# Generated by Django 3.2 on 2021-06-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0013_alter_file_f_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='key',
            field=models.CharField(default='.', max_length=200),
        ),
    ]
