# Generated by Django 3.2 on 2021-06-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0014_file_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='loc',
            new_name='url',
        ),
    ]
