# Generated by Django 3.2 on 2021-06-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0015_auto_20210603_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='text',
            field=models.CharField(max_length=30),
        ),
    ]
