# Generated by Django 3.2 on 2021-06-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0016_alter_file_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='text',
            field=models.FileField(max_length=30, upload_to=''),
        ),
    ]
