# Generated by Django 3.2 on 2021-06-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0017_alter_file_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=1, max_length=30, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
