# Generated by Django 3.2 on 2021-05-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='spouse_name',
        ),
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
    ]
